/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cwp.gui;

import java.sql.*;

/**
 *
 * @author Kenny
 */
public class studentScores extends javax.swing.JFrame{

	/**
	 * Creates new form studentScores
	 */
	public studentScores(){
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          panel = new javax.swing.JPanel();
          label_StudentNumber = new javax.swing.JLabel();
          text_StudentNumber = new javax.swing.JTextField();
          buttonSubmit = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          panel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

          label_StudentNumber.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
          label_StudentNumber.setText("Student Number:");

          text_StudentNumber.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

          buttonSubmit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
          buttonSubmit.setText("Submit");
          buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonSubmitActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
          panel.setLayout(panelLayout);
          panelLayout.setHorizontalGroup(
               panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(label_StudentNumber)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(buttonSubmit)
                         .addComponent(text_StudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(270, Short.MAX_VALUE))
          );
          panelLayout.setVerticalGroup(
               panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(label_StudentNumber)
                         .addComponent(text_StudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(buttonSubmit)
                    .addContainerGap(316, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
		String studentNumber = text_StudentNumber.getText().toString();

		try{
			String myDriver = "org.gjt.mm.mysql.Driver";
			String myUrl = "jdbc:mysql://localhost/cwp";
			Class.forName(myDriver);
			Connection conn1 = DriverManager.getConnection(myUrl, "root", "kc2269");
			if(conn1 != null){
				// our SQL SELECT query.
				// if you only need a few columns, specify them by name instead of using "*"
				String query = "SELECT * "
					+ "FROM students a, scores b"
					+ "WHERE a.student_num = :studentNum AND"
					+ "b.student_num = :studentNum;";

				Statement stmt = conn1.createStatement();
				// create the java statement
				Statement st = conn1.createStatement();

				// execute the query, and get a java resultset
				//ResultSet rs = st.executeQuery(selectQuery);
				//int result = st.executeUpdate(insertQuery);
				//System.out.println(result + " records were updated");
			}
			/*
			 * // iterate through the java resultset while(rs.next()){
			 * BigDecimal studentNum = rs.getBigDecimal("student_num");
			 * String firstName = rs.getString("fname"); String lastName =
			 * rs.getString("lname");
			 *
			 * // print the results System.out.format("%s, %s, %s\n",
			 * studentNum, firstName, lastName); }
			 */
		}catch(ClassNotFoundException | SQLException e){
			System.out.println("This error was given: " + e.getMessage());
		}

     }//GEN-LAST:event_buttonSubmitActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]){

		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try{
			for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
				if("Nimbus".equals(info.getName())){
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}catch(ClassNotFoundException ex){
			java.util.logging.Logger.getLogger(studentScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}catch(InstantiationException ex){
			java.util.logging.Logger.getLogger(studentScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}catch(IllegalAccessException ex){
			java.util.logging.Logger.getLogger(studentScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}catch(javax.swing.UnsupportedLookAndFeelException ex){
			java.util.logging.Logger.getLogger(studentScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable(){
			public void run(){
				new studentScores().setVisible(true);
			}
		});
	}

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton buttonSubmit;
     private javax.swing.JLabel label_StudentNumber;
     private javax.swing.JPanel panel;
     private javax.swing.JTextField text_StudentNumber;
     // End of variables declaration//GEN-END:variables
}
